name: yuix
description: "A new Flutter project Anime and Manga."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  salomon_bottom_bar: ^3.3.2
  iconsax: ^0.0.8
  provider: ^6.1.2
  # carousel_slider: ^5.0.0
  carousel_slider_plus: ^7.0.1
  dio: ^5.7.0
  graphql_flutter: ^5.1.2
  get: ^4.6.6
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
flutter_native_splash:
  image: assets/main/logo2.png
  color: "#000000"
flutter:
  uses-material-design: true
