// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PUd6xdCn5_h3skT1dwWo_uL_qQqui2w',
    appId: '1:843181165615:web:34b9bb169e5b968759cada',
    messagingSenderId: '843181165615',
    projectId: 'yuix-68908',
    authDomain: 'yuix-68908.firebaseapp.com',
    storageBucket: 'yuix-68908.firebasestorage.app',
    measurementId: 'G-CP3GXN0E52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1gU4_dUpxm16z-UEDXAkTDcJzN3FvCBQ',
    appId: '1:843181165615:android:ed2e6636bce5e91459cada',
    messagingSenderId: '843181165615',
    projectId: 'yuix-68908',
    storageBucket: 'yuix-68908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrA1HOYfZtEtr0oMQxMtu2jFGxRnyOv_s',
    appId: '1:843181165615:ios:39d6eae9766f168559cada',
    messagingSenderId: '843181165615',
    projectId: 'yuix-68908',
    storageBucket: 'yuix-68908.firebasestorage.app',
    iosBundleId: 'com.anime.yuix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrA1HOYfZtEtr0oMQxMtu2jFGxRnyOv_s',
    appId: '1:843181165615:ios:27ca4575b5e787c559cada',
    messagingSenderId: '843181165615',
    projectId: 'yuix-68908',
    storageBucket: 'yuix-68908.firebasestorage.app',
    iosBundleId: 'com.example.aurora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0PUd6xdCn5_h3skT1dwWo_uL_qQqui2w',
    appId: '1:843181165615:web:42a803c5106cd42859cada',
    messagingSenderId: '843181165615',
    projectId: 'yuix-68908',
    authDomain: 'yuix-68908.firebaseapp.com',
    storageBucket: 'yuix-68908.firebasestorage.app',
    measurementId: 'G-J37YMFVK15',
  );
}
